config/routes.rb
Rails.application.routes.draw do
  patch 'update_theme', to: 'themes#update'
  resources :projects
  devise_for :admins
  resources :contact_forms
  get 'home/index', controller: 'home', action: 'index'
  get 'up' => 'rails/healh#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_form.rb
class ContactForm < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @contact_form = ContactForm.new
  end
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  before_action :set_contact_form, only: %i[show edit update destroy]
  before_action :authenticate_admin!, only: %i[index show edit update destroy]

  # GET /contact_forms or /contact_forms.json
  def index
    @contact_forms = ContactForm.all
    @contact_forms = @contact_forms.order(sort_column => sort_direction)
  end

  # GET /contact_forms/1 or /contact_forms/1.json
  def show; end

  # GET /contact_forms/new
  def new
    @contact_form = ContactForm.new
  end

  # GET /contact_forms/1/edit
  def edit; end

  # POST /contact_forms or /contact_forms.json
  def create
    @contact_form = ContactForm.new(contact_form_params)

    respond_to do |format|
      if @contact_form.save
        format.html { redirect_to root_path, notice: 'Your message was sent!' }
        format.json { render :show, status: :created, location: @contact_form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_forms/1 or /contact_forms/1.json
  def update
    respond_to do |format|
      if @contact_form.update(contact_form_params)
        format.html { redirect_to contact_form_url(@contact_form), notice: 'Contact form was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_forms/1 or /contact_forms/1.json
  def destroy
    @contact_form.destroy!

    respond_to do |format|
      format.html { redirect_to contact_forms_url, notice: 'Contact form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact_form
    @contact_form = ContactForm.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_form_params
    params.require(:contact_form).permit(:email, :subject, :message)
  end

  def sort_column
    allowed_columns = %w[title price created_at]
    allowed_columns.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact_form = ContactForm.new
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:title, :github, :description, :youtube)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  def update
    session[:theme] = params[:theme]
    render turbo_stream: turbo_stream.replace(
      'theme-toggle',
      partial: 'themes/theme_toggle',
      locals: { theme: session[:theme] }
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
  def sortable(column, header = nil)
    allowed_columns = %w[created_at]
    header ||= column
    if allowed_columns.include?(column)
      direction = column == params[:sort] && params[:direction] == 'asc' ? 'desc' : 'asc'
      link_to header, sort: column, direction:
    else
      header
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contact_forms/_contact_form.html.erb
<div id="<%= dom_id contact_form %>">
  <div class="divider divider-start">
    <%= contact_form.created_at.to_formatted_s(:short)%>
  </div>
  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= contact_form.email %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Subject:</strong>
    <%= contact_form.subject %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Message:</strong>
    <%= contact_form.message %>
  </p>
</div>

app/views/contact_forms/_form.html.erb
<%= form_with(model: contact_form, local: true) do |form| %>
  <% if local_assigns[:expense] && contact_form.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>
      <ul>
        <% contact_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="group my-8">
    <%= form.text_field :email, class: "input rounded-none", required:true, type:"email" %>
    <span class="highlight"></span>
    <span class="bar"></span>
    <label>email</label>
  </div>
  <div class="group my-8">
    <%= form.text_field :subject, class: "input rounded-none" , required:true%>
    <span class="highlight"></span>
    <span class="bar"></span>
    <label>subject</label>
  </div>
  <div class="group my-8">
    <%= form.text_area :message, rows: 5, class: "input textfield rounded-none" ,  required:true%>
    <span class="highlight"></span>
    <span class="bar"></span>
    <label>message</label>
  </div>
  <%= form.submit "Submit", class: "btn  submit btn-primary w-4/5 rounded mt-5" %>
<% end %>

app/views/contact_forms/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing contact form</h1>

  <%= render "form", contact_form: @contact_form %>

  <%= link_to "Show this contact form", @contact_form, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to contact forms", contact_forms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/contact_forms/index.html.erb
<div class="w-full">
  <div class="divider divider-start font-bold text-4xl font-mono pb-10">messages</div>
  <div class="dropdown dropdown-hover">
    <div tabindex="0" role="button" class="btn btn-ghost rounded-box m-1 text-lg">Sort</div>
    <ul tabindex="0" class="dropdown-content menu bg-base-100 rounded-box z-[1] w-52 p-2 shadow">
      <%= sortable "created_at", "Date Added" %>
    </ul>
  </div>
  <% content_for :title, "Contact forms" %>
  <div id="contact_forms" class="min-w-full">
    <% @contact_forms.each do |contact_form| %>
      <div class="card shadow-xl border-base-300 mb-10 p-10">
        <%= render contact_form %>
        <p>
          <%= link_to "Show this contact form", contact_form, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/contact_forms/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New contact form</h1>

  <%= render "form", contact_form: @contact_form %>

  <%= link_to "Back to contact forms", contact_forms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/contact_forms/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @contact_form %>
    <%= link_to "Edit this contact form", edit_contact_form_path(@contact_form), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to contact forms", contact_forms_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this contact form", @contact_form, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>

app/views/home/_3d_card.html.erb
<div class="card" data-turbo="false">
  <!-- Front Side -->
  <div class="card-front">
    <div class="card-info">
      <%= image_tag("ProfilePicture.jpg", class: "mask") %>
      <div class="card-title">Adam LaBarge</div>
      <div class="card-subtitle">Software Engineer</div>
    </div>
    <ul class="card-social">
      <li class="card-social__item">
        <a href="http://www.github.com/adamlabarge" target="_blank">
          <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M12.026 2C7.13295 1.99937 2.96183 5.54799 2.17842 10.3779C1.395 15.2079 4.23061 19.893 8.87302 21.439C9.37302 21.529 9.55202 21.222 9.55202 20.958C9.55202 20.721 9.54402 20.093 9.54102 19.258C6.76602 19.858 6.18002 17.92 6.18002 17.92C5.99733 17.317 5.60459 16.7993 5.07302 16.461C4.17302 15.842 5.14202 15.856 5.14202 15.856C5.78269 15.9438 6.34657 16.3235 6.66902 16.884C6.94195 17.3803 7.40177 17.747 7.94632 17.9026C8.49087 18.0583 9.07503 17.99 9.56902 17.713C9.61544 17.207 9.84055 16.7341 10.204 16.379C7.99002 16.128 5.66202 15.272 5.66202 11.449C5.64973 10.4602 6.01691 9.5043 6.68802 8.778C6.38437 7.91731 6.42013 6.97325 6.78802 6.138C6.78802 6.138 7.62502 5.869 9.53002 7.159C11.1639 6.71101 12.8882 6.71101 14.522 7.159C16.428 5.868 17.264 6.138 17.264 6.138C17.6336 6.97286 17.6694 7.91757 17.364 8.778C18.0376 9.50423 18.4045 10.4626 18.388 11.453C18.388 15.286 16.058 16.128 13.836 16.375C14.3153 16.8651 14.5612 17.5373 14.511 18.221C14.511 19.555 14.499 20.631 14.499 20.958C14.499 21.225 14.677 21.535 15.186 21.437C19.8265 19.8884 22.6591 15.203 21.874 10.3743C21.089 5.54565 16.9181 1.99888 12.026 2Z"></path>
          </svg>
        </a>
      </li>
      <li class="card-social__item">
        <a href="http://www.twitter.com/adammlabarge" target="_blank">
          <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M20.875 7.5v.563c0 3.28-1.18 6.257-3.54 8.93C14.978 19.663 11.845 21 7.938 21c-2.5 0-4.812-.687-6.937-2.063.5.063.86.094 1.078.094 2.094 0 3.969-.656 5.625-1.968a4.563 4.563 0 0 1-2.625-.915 4.294 4.294 0 0 1-1.594-2.226c.375.062.657.094.844.094.313 0 .719-.063 1.219-.188-1.031-.219-1.899-.742-2.602-1.57a4.32 4.32 0 0 1-1.054-2.883c.687.328 1.375.516 2.062.516C2.61 9.016 1.938 7.75 1.938 6.094c0-.782.203-1.531.609-2.25 2.406 2.969 5.515 4.547 9.328 4.734-.063-.219-.094-.562-.094-1.031 0-1.281.438-2.36 1.313-3.234C13.969 3.437 15.047 3 16.328 3s2.375.484 3.281 1.453c.938-.156 1.907-.531 2.907-1.125-.313 1.094-.985 1.938-2.016 2.531.969-.093 1.844-.328 2.625-.703-.563.875-1.312 1.656-2.25 2.344z"></path>
          </svg>
        </a>
      </li>
      <li class="card-social__item">
        <a href="https://www.linkedin.com/in/adam-labarge-b8099182/" target="_blank">
          <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M19.547 3c.406 0 .75.133 1.031.398.281.266.422.602.422 1.008v15.047c0 .406-.14.766-.422 1.078a1.335 1.335 0 0 1-1.031.469h-15c-.406 0-.766-.156-1.078-.469C3.156 20.22 3 19.86 3 19.453V4.406c0-.406.148-.742.445-1.008C3.742 3.133 4.11 3 4.547 3h15zM8.578 18V9.984H6V18h2.578zM7.36 8.766c.407 0 .743-.133 1.008-.399a1.31 1.31 0 0 0 .399-.96c0-.407-.125-.743-.375-1.009C8.14 6.133 7.813 6 7.406 6c-.406 0-.742.133-1.008.398C6.133 6.664 6 7 6 7.406c0 .375.125.696.375.961.25.266.578.399.984.399zM18 18v-4.688c0-1.156-.273-2.03-.82-2.624-.547-.594-1.258-.891-2.133-.891-.938 0-1.719.437-2.344 1.312V9.984h-2.578V18h2.578v-4.547c0-.312.031-.531.094-.656.25-.625.687-.938 1.312-.938.875 0 1.313.578 1.313 1.735V18H18z"></path>
          </svg>
        </a>
      </li>
    </ul>
    <ul class="card-social see-more mb-16 card-subtitle right-0 bottom-0">
      <li class="card-social__item ">
        <div class="see-more-button text-md link underline-offset-8">about me</div>
      </li>
    </ul>
  </div>
  <%= render 'card_back'%>
</div>
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const cards = document.querySelectorAll(".card");

    cards.forEach((card) => {
      const seeMoreButton = card.querySelector(".see-more-button");
      const flipBackButton = card.querySelector(".flip-back");
      const backToCardButton = card.querySelector(".back-to-card-button");

      // Flip to show the back side
      seeMoreButton.addEventListener("click", () => {
        card.classList.add("flipped-horizontal");
        card.classList.remove("flipped-vertical");
      });


      // Flip back to the front side
      flipBackButton.addEventListener("click", () => {
        card.classList.remove("flipped-horizontal");
      });

    });
  });
</script>

app/views/home/_card_back.html.erb
<div class="card-back">
  <div class="card-subtitle left-0 pl-10 pt-8 top-0 text-lg">
    <div class="flip-back link font-bold no-underline">
      <--
    </div>
        <!-- Flex container to display timeline and contact form side by side -->
        <div class="flex w-full h-full gap-6">
          <!-- Left side: Timeline -->
          <div class="w-3/5">
            <%= render 'timeline' %>
          </div>
          <!-- Right side: Contact Form -->
          <div class="w-2/5">
            <turbo-frame id="form">
              <%= render 'contact_forms/form', contact_form: @contact_form %>
            </turbo-frame>
          </div>
        </div>
      </div>
    </div>

app/views/home/_contact.html.erb
<div class="hero-content flex-col lg:flex-row-reverse " id="contact">
  <div class="text-center lg:text-left ">
    <h1 class="text-5xl font-bold">Contact me</h1>
    <p class="py-6">If you would like to learn more about me, feel free to send me a message!</p>
  </div>
  <div class="card shrink-0 w-full max-w-lg shadow-2xl bg-base-100 mr-10">
    <form class="card-body">
      <div class="form-control">
        <input type="email" placeholder="email" class="input input-bordered" required />
      </div>
      <div class="form-control">
        <input type="text" placeholder="subject" class="input input-bordered" required />
      </div>
      <div class="form-control">
        <textarea placeholder="message" class="textarea textarea-bordered h-48" required></textarea>
      </div>
      <div class="form-control mt-6">
        <button class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>

app/views/home/_flash.html.erb
<% if notice.present? %>
  <div data-controller="notice" role="notice" class="alert alert-success w-1/4 drop-shadow-md fixed top-4 right-4 z-50">
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div data-controller="alert" role="alert" class="alert alert-success opacity-90 w-1/4 drop-shadow-md fixed top-4 right-4 z-50">
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <%= alert %>
  </div>
<% end %>

app/views/home/_railscourses_project.html.erb
<div class="mockup-browser border bg-base-300">
  <div class="mockup-browser-toolbar ">
    <a class="input" href="http://www.railscourses.com">http://www.railscourses.com</a>
  </div>
  <div class="flex justify-center -py-5 bg-base-200">
    <%= image_tag 'RailsCourses.png'%>
  </div>
</div>

app/views/home/index.html.erb
<div >
  <%= render  '3d_card'%>
</div>

app/views/layouts/_navbar.html.erb
<div class="flex justify-center fixed top-0 left-0 right-0 pt-2 z-30">
  <ul class="menu bg-base-200 menu-horizontal rounded-box drop-shadow-md flex-nowrap">
    <li>
      <a href="/" class="no-hover group">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 md:h-6 md:w-6 group-hover:text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
        home
      </a>
    </li>
    <li>
      <a href="/#timeline" class="no-hover group">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 md:h-6 md:w-6 group-hover:text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        about
      </a>
    </li>
    <!-- <li> -->
    <!--   <a href="/projects" class="no-hover group"> -->
    <!--     <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 md:h-6 md:w-6 group-hover:text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg> -->
    <!--     projects -->
    <!--   </a> -->
    <!-- </li> -->
    <% if admin_signed_in? %>
      <li>
        <a href="/contact_forms"class="group mx-1 md:mx-2 transition-colors duration-300 no-hover" aria-label="Messages">
          <svg class="w-5 h-5 md:w-6 md:h-6 fill-current group-hover:text-blue-500" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M20 4H4C2.897 4 2 4.897 2 6v12c0 1.103.897 2 2 2h16c1.103 0 2-.897 2-2V6c0-1.103-.897-2-2-2zm0 2v.511l-8 4.8-8-4.8V6h16zM4 18V8.402l8 4.8 8-4.8V18H4z"></path>
          </svg>
          messages
        </a>
      </li>
      <li>
        <div class="hover:bg-red-500 hover:text-white"><%= button_to "Log Out", destroy_admin_session_path, method: :delete %></div>
      </li>
    <% else %>
      <li>
        <a onclick="contact_modal.showModal()" class="group mx-1 md:mx-2 transition-colors duration-300 no-hover" aria-label="Contact Me">
          <svg class="w-5 h-5 md:w-6 md:h-6 fill-current group-hover:text-blue-500" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M20 4H4C2.897 4 2 4.897 2 6v12c0 1.103.897 2 2 2h16c1.103 0 2-.897 2-2V6c0-1.103-.897-2-2-2zm0 2v.511l-8 4.8-8-4.8V6h16zM4 18V8.402l8 4.8 8-4.8V18H4z"></path>
          </svg>
          contact
        </a>
      </li>
    <% end%>
    <li>
      <label class="swap swap-rotate">
        <input type="checkbox" class="theme-controller opacity-0" value="business" />
          <svg
            class="swap-on h-6 w-6 fill-current"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24">
            <path
              d="M5.64,17l-.71.71a1,1,0,0,0,0,1.41,1,1,0,0,0,1.41,0l.71-.71A1,1,0,0,0,5.64,17ZM5,12a1,1,0,0,0-1-1H3a1,1,0,0,0,0,2H4A1,1,0,0,0,5,12Zm7-7a1,1,0,0,0,1-1V3a1,1,0,0,0-2,0V4A1,1,0,0,0,12,5ZM5.64,7.05a1,1,0,0,0,.7.29,1,1,0,0,0,.71-.29,1,1,0,0,0,0-1.41l-.71-.71A1,1,0,0,0,4.93,6.34Zm12,.29a1,1,0,0,0,.7-.29l.71-.71a1,1,0,1,0-1.41-1.41L17,5.64a1,1,0,0,0,0,1.41A1,1,0,0,0,17.66,7.34ZM21,11H20a1,1,0,0,0,0,2h1a1,1,0,0,0,0-2Zm-9,8a1,1,0,0,0-1,1v1a1,1,0,0,0,2,0V20A1,1,0,0,0,12,19ZM18.36,17A1,1,0,0,0,17,18.36l.71.71a1,1,0,0,0,1.41,0,1,1,0,0,0,0-1.41ZM12,6.5A5.5,5.5,0,1,0,17.5,12,5.51,5.51,0,0,0,12,6.5Zm0,9A3.5,3.5,0,1,1,15.5,12,3.5,3.5,0,0,1,12,15.5Z" />
          </svg>
          <svg
            class="swap-off h-6 w-6 fill-current"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24">
            <path
              d="M21.64,13a1,1,0,0,0-1.05-.14,8.05,8.05,0,0,1-3.37.73A8.15,8.15,0,0,1,9.08,5.49a8.59,8.59,0,0,1,.25-2A1,1,0,0,0,8,2.36,10.14,10.14,0,1,0,22,14.05,1,1,0,0,0,21.64,13Zm-9.5,6.69A8.14,8.14,0,0,1,7.08,5.22v.27A10.15,10.15,0,0,0,17.22,15.63a9.79,9.79,0,0,0,2.1-.22A8.11,8.11,0,0,1,12.14,19.73Z" />
          </svg>
        </label>
    </li>
  </ul>
</div>
<dialog id="contact_modal" class="modal">
  <div class="modal-box w-11/12 max-w-5xl">
    <%= render 'contact_forms/form', contact_form: @contact_form %>
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full pb-20">
  <h1 class="font-bold text-4xl">Editing project</h1>
  <%= render "form", project: @project %>
  <%= link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full pb-10">
  <%= render "form", project: @project %>
  <%= link_to "Back to projects", projects_path, class: " ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex pb-20">
  <div class="mx-auto">
    <%= render @project %>
    <%= link_to "Edit this project", edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this project", @project, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>